### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by chrisdrobison** [kelp404/angular-form-builder#80]
Seems like the project maintainer won't be doing anything on this (at least that is my perception seeing as how there are open pull requests and issues that have gone unanswered for a while). Has anyone else forked this to continue the project?

**Comment by huei90** [comment]
@kelp404

**Comment by darrencauthon** [comment]
I don't understand. Just because something has not updated in a while doesn't mean it's "dead."  It does what it needs to do just fine. If you need it to do more, don't look for forks... Press the fork button and get to it.

**Comment by chrisdrobison** [comment]
I think you misunderstand. I would like to contribute to this project, but seeing as how the maintainer doesn't seem to respond to issues or pull requests, this project for all intents and purposes, is dead. You can't contribute when it will never get merged in. Forking and doing my own thing would be pointless as I would be off on my own rather than working in conjunction with a community. Hence this "issue" to find out if someone else has already taken it upon themselves to try and maintain this project and continue to build it.

**Comment by darrencauthon** [comment]
> Forking and doing my own thing would be pointless as I would be off on my own rather than working in conjunction with a community. 

This is not true.  This is Github, not SourceForge.  If there's a community around a project, they can work around anybody -- including the original author.  There are cases where a fork of a project of a so-called "dead" project becomes more popular than the original author's repo.  

Plus, it's not "pointless" if the changes you make have value to you.  If you want the library to do something, you must have some **need**.  If you write the code to fill that need, how can it be pointless?  **You** got something out of it.  You got the benefit of the project giving you a huge head-start, and you received the benefit of your own contribution.  If the original author doesn't merge the changes in, that's their loss - not yours.  They don't owe you anything, you don't owe them anything... it's really all about the code.  

So instead of putting out a ticket that pokes the author.. why not write code?  Like... right now, instead of even writing a response to this with more talky talky talky talky... put hands on a keyboard and type code with fingers that make your fork better.

**Comment by huei90** [comment]
@chrisdrobison @darrencauthon I think we don't need to argue around this topic "Is dead"
We can found a lot "Is dead" article within all github repo.

See how others fork the project
https://github.com/kelp404/angular-form-builder/network

We all believe that we can make the open source projects become better and better. Looking at the PR and issue, we see the author didn't update them, what should we do next?

Ask the author to give permission for the collaborator/maintainer, send the author a message/email to ask what's going on, fork the repo and fix the bug.

Seems angular-form-builder is very useful and powerful project, we all believe that it's still "alive" :smile:
